### ISSUE TITLE
Error: "No directory, logging in with HOME=/"

### ISSUE THREAD

**Issue by kallaguntamanojkumar** [miztiik/DevOps-Demos#1]
I have run the below-mentioned commands:
   # Create user and add the user to wheel group
   useradd jenkins-slave-01
   # Create SSH Keys
   sudo su - jenkins-slave-01

But i got the below error:
"No directory, logging in with HOME=/"

Could you please help me with this

**Comment by miztiik** [comment]
Are you using the same OS as the demo suggests?

In any case you can recreate the [UID & home directory of your unix flavor](https://www.google.com/search?q=create+user+and+home+directory+linux&oq=create+user+and+home+&aqs=chrome.0.0j69i57j0l4.4375j0j7&sourceid=chrome&ie=UTF-8)

**Comment by miztiik** [comment]
Closing as no response
